### ISSUE TITLE
transpile arg file is not a TextIO

### ISSUE THREAD

**Issue by jayvdb** [Coronon/PySchemeTranspiler#1]
The static function transpile says the arg `file` is of type `TextIO`, however it tries to access member `.name`, which is a `FileIO` property.

**Comment by Coronon** [comment]
Hi there, thanks for letting me know. Would you mind supplying a little piece of code so that I can replicate this issue?

**Comment by jayvdb** [comment]
https://github.com/Coronon/PySchemeTranspiler/blob/1d41108/PySchemeTranspiler/converter.py#L26 should be [`FileIO`](https://docs.python.org/3/library/io.html#raw-file-i-o), not `TextIO`.

```py
from PySchemeTranspiler.converter import Converter
code = unparse(node)
buf = io.StringIO(code)
buf.name = str(node.__file__)
out = Converter.transpile(buf)
```

**Comment by Coronon** [comment]
This does indeed seem to be a bug (at least not at runtime ^^). I can fix it or you could submit a PR if you would like :) Did you use MyPy to catch this? Im pretty sure I used it in development, which is why this catches me off guard.

**Comment by Coronon** [comment]
This is actually not a bug. You confused the `io` and `typing` packages. `TextIO` is indeed the correct type here: https://docs.python.org/3/library/typing.html#typing.IO

The documented note however explains the confusion: The std::io library was never compatible with type checking which is why these have nearly the same name but different meanings.

**Comment by jayvdb** [comment]
oh, sorry about that!  Very confusing.
