### ISSUE TITLE
Recursive fib.py hangs

### ISSUE THREAD

**Issue by jayvdb** [Coronon/PySchemeTranspiler#3]
https://github.com/adsharma/py2many/blob/main/tests/cases/fib.py transpiles to the following, which hangs

```racket
#lang racket
(define (PRINT . args) (for-each (lambda (x) (display x) (display " ")) args)(newline))
(define (== a b) (if (and (number? a) (number? b)) (= a b) (equal? a b)))
(define (!= a b) (if (and (number? a) (number? b)) (not (= a b)) (not (equal? a b))))

(define (fib i) (cond ((or (== i 0) (== i 1)) 1))(+ (fib (- i 1)) (fib (- i 2))))
(cond (#t (PRINT (fib 5))))
```

**Comment by Coronon** [comment]
This is the expected behaviour. Please carefully read the section on if statements in the documentation. While you do not need an else in Python, this is required here as scheme (racket) always returns the last “element” in a function. Therefore the fib function would never `return 1` here as it is not the last element considering `return` would not interrupt the control flow.

Documentation: https://github.com/Coronon/PySchemeTranspiler#multiple-returns

**Comment by jayvdb** [comment]
Thanks.  It would be helpful to detect incompatible use of `return` and raise an exception during transpilation. If this isnt a priority for you, I could implement that in the py2many wrapper I've been creating.

**Comment by Coronon** [comment]
I had to use Racket for school work and didn’t like it, which is why I created PYST. I’ll have a look at integrating this. This does however appear to be quite difficult. Take this scenario:

```py
def f() -> int:
    if exp1:
        if exp2:
            return 1
        else:
            return 2
    
     return 0
```

Here R1 and R2 are correctly in an if/else but we are also in an outer if. I could try to utilise the build in if scope tracking (used to define variables).

I’ll have a go tonight probably, but this will most likely stay on PY8.

PS: the normal syntax is actually quite easy to implement (no need for else), it would however come at quite a performance impact.

**Comment by Coronon** [comment]
What do you think about the following: We only allow `return` as the last statement in any function. This would mean multiple return values would need a tmp storage and force most sensible developers to use if/else correctly. The above xample would become:

```py
def f() -> int:
    if exp1:
        if exp2:
            ret = 1
        else:
            ret = 2
    
     ret = 0 #<- This is an obivous bug, which is why everyone would put 'else' correctly
     return ret
```

Catching this:
```py
def fib(i: int) -> int:
    if i == 0 or i == 1:
        return 1
    
    return fib(i - 1) + fib(i - 2)
```
is actually quite easy to do:
```
[ValueError] Invalid use of multiple returns: https://github.com/Coronon/PySchemeTranspiler#multiple-returns
4>0:  def fib(i: int) -> int:
```
The only problematic nodes are nested ifs

**Comment by jayvdb** [comment]
I'll be happy if my case fails instead of hanging.

But your suggestion above for nested if's doesnt look like it would be enough to prevent emitting code which hangs.  You may want to create a separate issue for that, and come back to it later.

**Comment by Coronon** [comment]
Recursive ifs do emit warnings now. Im now looking into loops and statements after a return in an if

UPDATE: Loops seem solved

**Comment by Coronon** [comment]
DONE! Please pull the repo and have a look at my changes. This should cover if/elif/else (nested), loops and expressions after `return`. Thanks for letting me know about the issue :)
